### ISSUE TITLE
feature request: undecorate all windows, not just maximized

### ISSUE THREAD

**Issue by evan-phelps** [deadalnix/pixel-saver#60]
It would be great to have an option to remove window decorations _even for unmaximized windows_.  I previously achieved this through the metacity configuration, but this approach is not applicable in recent versions of gnome-shell that use gtk.css.

**Comment by deadalnix** [comment]
I'm not sure how that fit the extension's goal. If the window is not maximized, then it is fair to assume saving pixel is not priority.

**Comment by evaryont** [comment]
Would you consider re-opening this? I use [shellshape](http://gfxmonk.net/shellshape/) with gaps. I like my background image -- so the windows are almost never maximized. Along with that, I rely on [conky](https://github.com/brndnmtthws/conky) as well. In that situation, I'd think it'd be very much in the spirit of the project's name that I want to save pixel space even more so, since the windows are even smaller.
